### ISSUE TITLE
Not Found response when mounting a Rack app into Lotus container

### ISSUE THREAD

**Issue by midas** [lotus/lotus#121]
Given a container configuration:

```
Lotus::Container.configure do
  mount Web::Application, at: '/'
  mount ->(env) {[200, {}, ['Rack Four']]},  at: '/rack'
end
```

After starting server, perform a curl request:

```
curl -H Accept:application/json -H Content-Type:application/json http://localhost:2300/rack
```

Results in a `Not Found`.

Environment information follows.

```
ruby -v
ruby 2.1.5p273 (2014-11-13 revision 48405) [x86_64-darwin14.0]
```

```
bundle show
  ...
  * lotus-controller (0.3.0)
  * lotus-model (0.2.0)
  * lotus-router (0.2.0)
  * lotus-utils (0.3.2)
  * lotus-validations (0.2.1)
  * lotus-view (0.3.0)
  * lotusrb (0.2.0)
  ...
  * rack (1.6.0)
  * rack-accept (0.4.5)
  * rack-mount (0.8.3)
  * rack-test (0.6.2)
```

**Comment by jodosha** [comment]
@midas Thanks for reporting this. The problem is that the first application will capture all the requests who match the defined root `/`. So when you try to reach `/rack`, this resource is shadowed by the first application, which doesn't define that resource and returns a `404`.

This is a well known limitation, and the solution is in our [backlog](https://trello.com/c/LbpVBQuL/23-flatten-routes).

It isn't high priority for now, because the solution is easy: put the most _"greedy"_ routes at the bottom.

Example:

```ruby
Lotus::Container.configure do
  mount ->(env) {[200, {}, ['Rack Nested']]},  at: '/rack/nested'
  mount ->(env) {[200, {}, ['Rack Four']]},  at: '/rack'
  mount Web::Application, at: '/'
end
```

I understand that this is counterintuitive at the beginning, and I'm sorry for this problem. Let me know if I can help with anything else.

**Comment by midas** [comment]
@jodosha Thanks for the reply.  This makes sense.  Also, thanks for your work on this awesome framework.  I would love to get involved if possible.  How does one go about getting involved at this point?

Thanks!

**Comment by joneslee85** [comment]
@midas Greetings! We welcome contributions in any means. @jodosha's posted Lotus Roadmap 2015 and there are much works to be done. For the time being, please feel free to join chat.lotusrb.org and let us know if you are interested in picking up any planned features.
