### ISSUE TITLE
Flower-Power  - meta framework: a bridge between Lotus and Volt

### ISSUE THREAD

**Issue by alexsun** [lotus/lotus#150]
Hello World

The problem is important in web development. This is my summary for more than 15 years of my experience on the web development: from ASP, PHP4, plain HTML, CSS without firebug, more than 5 years with Drupal, this is a great and complex CMS/Framework, now learning in Ruby and C. 

This is not about blah-blah TODO.app on pure JS and fresh RIA (from Flash), or generation a flat single-page of html application with super-smart JS tools, that  be a very good in maintainable. Analogs all of this I had ten years ago, with opacity - oh this buzzwords :)

NEED modern the framework, that need for each Web Developer, in the Ruby Community.

I hope you have a minute to consider a idea, goals and problems:

https://github.com/alexsun/Flower-Power/blob/master/README.md

This description draft, not structured. Meager English, with interpreter; (maybe later I will find time for study English grammar, forgive me) 

plan in few days (weeks) add description, structure of goals and beautify with dummy examples of usage

I'm not want forking, pull two frameworks and do all in a solo, maybe have more better way?

any comments, critics, help, very welcome

[Volt issue: Flower-Power](https://github.com/voltrb/volt/issues/104)

**Comment by alexsun** [comment]
https://github.com/voltrb/volt/issues/104

**Comment by jodosha** [comment]
@alexsun Hello and thanks for starting this discussion.
I'm not sure I haven't got what are your goals. Partly because I don't know how Volt works in the low level details.

Our components can be reused to accomodate your needs. If you have any specific use case that those Lotus frameworks should support, please don't hesitate to open a ticket in the related repository.

I'm closing this for now, thank you.
