### ISSUE TITLE
Use .env at the root of the application

### ISSUE THREAD

**Issue by jodosha** [lotus/lotus#191]
Quoting a discussion from our chat:

  > @luislavena: any specific reason why .env information is looked up in `config/.env` instead of the root of the repository?
  > @jodosha: Hello, nope, only to keep all the confs under `config/`. If you are thinking about Heroku, please notice that `Lotus::Environment` reads `config/.env` and sets the env vars for you. It uses `Dotenv` internally.
  > @luislavena: thanks, was actually thinking on foreman and tools like azk and others that read repo's root for .env and allow you run one-off commands.

**Comment by joneslee85** [comment]
@jodosha @luislavena I'd leave it in `config` folder. Users can always point `foreman` and `azk` to this folder.

**Comment by jodosha** [comment]
What if devs can't do it? For instance in deployment envs.

http://lucaguidi.com

**Comment by joneslee85** [comment]
@jodosha I question if users should use `foreman` in deployment env or not.

**Comment by luislavena** [comment]
@joneslee85 @jodosha the main issue with `.env` inside `config` are:

- *dotfiles* inside anything other than `root` of your project are hard to spot.
- The default of foreman and azk look for `.env` at the root of your project
- Dotenv follows that and the usage recommendation is to place `.env` at the root of the project.

As you can see, there are several sources that can define `.env` placement in the root of your project as *standard*.

While `config` sound reasonable, we are forcing a different behavior than the one expected from these other tools.

To use foreman, azk or dotenv with a custom rake task in those scenarios I'll be forced to be explicit on the location of the env file instead of the assumed and documented default.

**Comment by joneslee85** [comment]
@luislavena the original intent is to have everything consolidated in 1 `config` folder, but now when I have more thought about this, the dotenv seems irrelevant to persistent config because it is not recommended to use it on production anyway. So sure, I'd vote :+1: moving them out to root.
