### ISSUE TITLE
Get rid of very long require_relative in tests

### ISSUE THREAD

**Issue by mli-max** [lotus/lotus#293]
I generated action with rspec test file and see on top of it:
```
require 'spec_helper'
require_relative '../../../../apps/web/views/dashboard/index'
```
But we have required `spec_helper` in `.rspec`, so I remove first line and test passed.
I don't like this long require_relative, I have found solution!

We put that line in `spec_helper`
`ROOT = Pathname(File.expand_path(File.join(__dir__, '..')))`

and then in test
`require ROOT.join('apps/web/controllers/dashboard/index')`

Or we can create something like Rails does.
`Lotus.root`

**Comment by mli-max** [comment]
@jodosha Why we have this method private?
```
# @since 0.3.0
      # @api private
      def app_root
        @app_root ||= begin
          result = Pathname.new(@options[:apps_path])
          result = result.join(@app_name) if @env.container?
          result
        end
      end
```

**Comment by jodosha** [comment]
@mli-max Thanks for opening this discussion. `require_relative` is faster than `require`, because the first looks up only for the path that you specify, while the latter has to look for the file in all the require paths (including all the gems in your app).

That line is there for ease TDD. When you run it via `bundle exec rspec path/to/index_spec.rb`, it will only load Lotus, the gem deps, but **NOT** your application code. That line will explicitely require your action, so it can be tested in isolation and faster.

As of [v0.3.2](https://github.com/lotus/lotus/blob/master/FEATURES.md#v032---2015-05-22) we have `Lotus.root` and it's public API.

We are conservative about public API. Unless there is a reason that requires devs to access a certain method, we mark it as private.
