### ISSUE TITLE
Error on session middleware and rspec 

### ISSUE THREAD

**Issue by vyper** [lotus/lotus#304]
I tested test version 0.4.1, but I got an errors... references to [other issue](https://github.com/lotus/lotus/issues/283).

# Using configuration

```ruby
sessions :cookie, secret: ENV['SESSIONS_SECRET']
middleware.use Rack::Session::Cookie, secret: ENV['SESSIONS_SECRET']
middleware.use OmniAuth::Builder do
  provider :facebook, ENV['FACEBOOK_KEY'], ENV['FACEBOOK_SECRET']
end
```

# Specs ran perfectly
```
rspec spec/web/features/login_spec.rb
.......

Finished in 0.95783 seconds (files took 0.91043 seconds to load)
7 examples, 0 failures

# Or this version
rspec spec/web/features/
.......

Finished in 0.95783 seconds (files took 0.91043 seconds to load)
7 examples, 0 failures
```

# Using "lotus way" configuration

```ruby
sessions :cookie, secret: ENV['SESSIONS_SECRET']
middleware.use OmniAuth::Builder do
  provider :facebook, ENV['FACEBOOK_KEY'], ENV['FACEBOOK_SECRET']
end
```

# Specs ran partially ):
```
rspec spec/web/features/login_spec.rb
.......

Finished in 0.95783 seconds (files took 0.91043 seconds to load)
7 examples, 0 failures

# But this version is strange
rspec spec/web/features/
FFFFFFF

Finished in 1.52 seconds (files took 0.95663 seconds to load)
7 examples, 7 failures
```

A sample for rspec exception:

```
Failures:

  1) Logging in from Twitter shows the user the welcome page
     Failure/Error: visit '/auth/facebook'
     OmniAuth::NoSessionError:
       You must provide a session to use OmniAuth.
     # ./.bundle/gems/omniauth-1.2.2/lib/omniauth/strategy.rb:175:in `call!'
     # ./.bundle/gems/omniauth-1.2.2/lib/omniauth/strategy.rb:164:in `call'
     # ./.bundle/gems/omniauth-1.2.2/lib/omniauth/builder.rb:59:in `call'
     # ./.bundle/gems/rack-1.6.4/lib/rack/builder.rb:153:in `call'
     # ./.bundle/gems/lotusrb-0.4.1/lib/lotus/middleware.rb:52:in `call'
     # ./.bundle/gems/lotusrb-0.4.1/lib/lotus/application.rb:217:in `call'
     # ./.bundle/gems/http_router-0.11.2/lib/http_router.rb:193:in `process_destination_path'
     # (eval):15:in `call'
     # ./.bundle/gems/http_router-0.11.2/lib/http_router.rb:288:in `raw_call'
     # ./.bundle/gems/lotus-router-0.4.2/lib/lotus/routing/http_router.rb:123:in `raw_call'
     # ./.bundle/gems/http_router-0.11.2/lib/http_router.rb:142:in `call'
```

**Comment by rpanachi** [comment]
I had a similar problem with `sessions` vs `middleware.use` with Redis.

Declaring `sessions` according with Lotus docs, fails os csrf_token verification (because session is always nil on controller):

```ruby
sessions :redis, secret: ENV['SESSIONS_SECRET']
```

But declaring `sessions` and `middleware` together, works fine:

```ruby
sessions :redis, secret: ENV['SESSIONS_SECRET']
middleware.use Rack::Session::Redis, secret: ENV['SESSIONS_SECRET']
```

I checked the method `_load_session_middleware` on file `lib/lotus/middleware.rb:107` and It seems to use the session middleware correctly. But still not working. Any ideas?

**Comment by jodosha** [comment]
@vyper Hello. I'm deeply sorry with this continue hassle that you have experienced with Lotus sessions.

By trying to reproduce this error locally, I ran into an issue. I setup my `spec/features_helper.rb` like this:

```ruby
# ...
OmniAuth.config.test_mode = true

OmniAuth.config.mock_auth[:facebook] = OmniAuth::AuthHash.new({
  :provider => 'facebook',
  :uid => '123545'
})
```

According to OmniAuth [wiki](https://github.com/intridea/omniauth/wiki/Integration-Testing):

> Once you have enabled test mode, all requests to OmniAuth will be short circuited to use the mock authentication hash as described below. A request to `/auth/provider` will redirect immediately to `/auth/provider/callback`.

My callback action looks like this:

```ruby
    def call(params)
      omniauth = request.env['omniauth.auth']

      if omniauth && uid = omniauth['uid']
        session[:user_id] = uid
        redirect_to routes.home_url
      else
        halt 401
      end
    end
```

If I debug, it successfully set `:user_id`, but after the redirect to the home page, the session is empty again. This causes an infinite loop, because the corresponding action, redirects to `/auth/fa

```
  1) Error:
Login#test_0001_logins:
Capybara::InfiniteRedirectError: redirected more than 5 times, check for infinite redirects.
    /Users/luca/.gem/ruby/2.2.3/gems/capybara-2.5.0/lib/capybara/rack_test/browser.rb:40:in `process_and_follow_redirects'
    /Users/luca/.gem/ruby/2.2.3/gems/capybara-2.5.0/lib/capybara/rack_test/browser.rb:21:in `visit'
    /Users/luca/.gem/ruby/2.2.3/gems/capybara-2.5.0/lib/capybara/rack_test/driver.rb:42:in `visit'
    /Users/luca/.gem/ruby/2.2.3/gems/capybara-2.5.0/lib/capybara/session.rb:232:in `visit'
    /Users/luca/.gem/ruby/2.2.3/gems/capybara-2.5.0/lib/capybara/dsl.rb:51:in `block (2 levels) in <module:DSL>'
    /Users/luca/Desktop/bookshelf/spec/web/features/login_spec.rb:5:in `block (2 levels) in <top (required)>'
```

Did you ran in the same issue? If so, how did you solved it?

**Comment by jodosha** [comment]
@vyper @rpanachi Here some extra debug informations, but we need your feedback, cause I wasn't able to reproduce this problem.

### Hypotesis 1: Session options

Here's a debug setup:

```ruby
# apps/web/application.rb
# ...
      sessions :cookie, secret: '123'

      middleware.use Rack::Session::Cookie, secret: '456'
      middleware.use OmniAuth::Builder do
        provider :facebook, ENV['FACEBOOK_KEY'], ENV['FACEBOOK_SECRET']
      end
```

So the stack is like this:

```ruby
(byebug) configuration.middleware.instance_variable_get(:@stack)
Rack::MethodOverride

Rack::Static
{:urls=>["/javascripts", "/stylesheets"], :root=>"/Users/luca/Desktop/bookshelf/apps/web/public"}

Rack::Session::Cookie
{:domain=>nil, :secure=>false, :secret=>"123"}

OmniAuth::Builder
#<Proc:0x007ffc4d1e6120@/Users/luca/Desktop/bookshelf/apps/web/application.rb:83>
Rack::Session::Cookie
{:secret=>"456"}
```

According to your bug report, by adding the session middleware explicitly in the stack, solves your problem. As you can see it appears after `OmniAuth::Builder`, so the sequence is: 1. omniauth 2. rack session (with `456` secret).

This extra session middleware, should be theoretically useless, because if you remove `sessions` configuration, OmniAuth complains with `OmniAuth::NoSessionError`

By restricting the scope of the problem, it may be that the different session configuration can cause problems. The default for `sessions` has three options:

  * `:domain` (`nil`, by default)
  * `:secure` (`false`, by default)
  * `:secret` (the one we specify in the configuration)

Can you please patch your `lotusrb` gem like this?

```ruby
# lib/lotus/config/sessions.rb
      def default_options
        if @configuration
          result = { secure: @configuration.ssl? }
          result.merge!(domain: domain) unless domain.nil?
          result
        else
          {}
        end
      end
```

I suspect that `:domain => nil` can be a source of trouble.

### Hypotesis 2: Wrong middleware loading order

As fix for #283 we introduced a different way to add middleware: by prepending it to the stack.
This may be a wrong policy.

Can you please verify how your application behaves with the following setup?

```ruby
# web/apps/application.rb
      middleware.use OmniAuth::Builder do
        provider :facebook, ENV['FACEBOOK_KEY'], ENV['FACEBOOK_SECRET']
      end
      middleware.use Rack::Session::Cookie, secret: '456'

# ...

      controller.prepare do
        include Web::Action::Session
      end
```

If this works just fine we should revert the fix (#302) and ensure that only `sessions` will prepend its middleware, in order to be used before OmniAuth.

---

Thanks for your patience and precious help. Please let me know if something isn't clear here :smile:

**Comment by rpanachi** [comment]
@jodosha thanks for the feedback. I tested your sugestions, and this is the results.

**Hypotesis 1**: patching the `sessions.rb` dont solve the problem and raises a `Lotus::Action::InvalidCSRFTokenError` on request (since the session could not be persisted, I guess).

Here is my `application.rb` setup:

```ruby
sessions :redis, secret: "1234", redis_server: "redis://localhost:6379/1/session"
```

And my middleware stack:

```ruby
Rack::MethodOverride

Rack::Static
{:urls=>["/assets"], :root=>"/home/user/projects/myapp/apps/admin/public"}

Rack::Session::Redis
{:secure=>false, :domain=>"http://localhost:2300/admin", :secret=>"1234", :redis_server=>"redis://localhost:6379/1/session"}

Rack::Logger
#<Logger:0x007f740a464260>
```


**Hypotesis 2**: actually worked, even without the `sessions` option. Here is my `application.rb` setup:

```ruby
middleware.use Rack::Session::Redis, secret: "1234", redis_server: "redis://localhost:6379/1/session"
controller.prepare do
   include Admin::Action::Session
end
```

And the middleware stack:

```ruby
Rack::MethodOverride

Rack::Static
{:urls=>["/assets"], :root=>"/home/user/projects/myapp/apps/admin/public"}

Rack::Logger
#<Logger:0x007f740a464260>

Rack::Session::Redis
{:secure=>false, :domain=>"http://localhost:2300/admin", :secret=>"1234", :redis_server=>"redis://localhost:6379/1/session"}
```

Correct me if I'm wrong, but I believe the Hypothesis 2 confirms that when setting the `sessions` option, the middleware is loaded in the wrong order. That's right? Is there any way I can help fix this issue? Thanks

**Comment by jodosha** [comment]
@rpanachi Thanks for your feedback, you helped to clarify what's wrong here.

My solution to prepend sessions middleware (#302) is wrong. I think the solution at this point is to follow the order of declaration that a dev follows and just make sure that `sessions :redis`, prepends its own middleware. Does it makes sense?

**Comment by pascalbetz** [comment]
@rpanachi 

can you help me reproduce the error? do you have a sample app for this?
i tried setting up a simple lotus app with sessions in redis. worked like a charm.
