### ISSUE TITLE
Action Generator generates new named routes

### ISSUE THREAD

**Issue by joneslee85** [lotus/lotus#337]
Action Generator

Now:

* Generate un-named routes, eg: `get '/hello', to: 'greetings#hello'`

Should:

* Generate named routes, eg `get '/hello', to: 'greetings#hello', as: 'hello_greetings'`

Why?

Named routes should be used in favour to nameless routes as centralise the route management, giving user access to routes via `routes` helper

**Comment by joneslee85** [comment]
cc @lotus/core-team - worth doing?

**Comment by AlfonsoUceda** [comment]
:+1: but for route helper always is a good option choose "action_controller" ?

**Comment by joneslee85** [comment]
@AlfonsoUceda can you please elaborate on `action_controller`?

**Comment by jodosha** [comment]
@AlfonsoUceda wuh :question:

**Comment by jodosha** [comment]
@joneslee85 I'd say no. Not all the routes need a name. If a dev needs a name, they can name as they want.

It's hard to predict what's a good name that would satisfy devs, because this is a matter of subjective taste. If we code an algo for that, we need to increase the complexity of the `lotus generate action` with another flag and add unnecessary weight to the router helpers.
