### ISSUE TITLE
.lotusrc double creation

### ISSUE THREAD

**Issue by aderyabin** [lotus/lotus#369]
Command `bundle exec lotus new blog` creates two `.lotusrc` files – in current and `./blog` directories. Does it correct?

**Comment by joneslee85** [comment]
it should create one

**Comment by jasoncharnes** [comment]
I don't mind taking a look at this.

**Comment by aderyabin** [comment]
OMG. `lotus help` generates `.lotusrc` file

**Comment by pascalbetz** [comment]
I already commented on this in another thread. Instantiating L:Lotusrc creates the file. I think this is done in order to provide a default file with default values.

In my opinion this is unexpected. The file should only be created by a dedicated method call. If the file is not there, then default values should be returned from L:Lotusrc.

See https://github.com/lotus/lotus/blob/master/lib/lotus/lotusrc.rb#L79
