### ISSUE TITLE
Implement observer pattern

### ISSUE THREAD

**Issue by samdvr** [lotus/lotus#390]
# Overview
Consider implementing event publishers and subscribers module similar to the
[Wisper](https://github.com/krisleech/wisper) gem. 
Implementing this feature will facilitates communication between decoupled objects.

## Details
Events can be emitted synchronously or asynchronously and backed by a message broker.
App folder then will have publishers folder and subscribers folder that encapsulate objects that emit events and interested listeners.

**Comment by jodosha** [comment]
@samdvr Hello. What's your use case for this? Why do you want the solution to be implemented by Lotus? Does Wisper missing features that you need?

**Comment by samdvr** [comment]
@jodosha  Hi. the main use case is decoupling events from business logic and avoiding callbacks. I think it would be a nice feature to include in Lotus as a default to promote best practices.
Also events can be communication mechanism between multiple apps.

**Comment by jodosha** [comment]
@samdvr 

> the main use case is decoupling events from business logic and avoiding callbacks.

Are you talking about models? Is your idea to overcome the absence of callbacks with observers?

**Comment by samdvr** [comment]
@jodosha yes that's one use case the other is communication between different apps. Similar to the way Erlang "applications" send messages to each other in a fire and forget fashion.

**Comment by jodosha** [comment]
@samdvr Business logic is handled all inside `lib/` in a Lotus project. Please remember that applications under `apps/` are there only to consume that business logic. So there aren't many applications that need to communicate each other, but only a few objects under `lib/`.

Observers are hard to debug and decrease code locality: an event could trigger zero to many actions defined somewhere else.

This collides with Lotus Interactors design: all the steps of an use case are defined locally and they work with message passing, which is simpler than send an event and hope that the recipient will receive it and execute.

Let me explain with an example (borrowed from Wisper README):

```ruby
class CancelOrder
  include Lotus::Interactor

  def initialize(order_id)
    @order_id = order_id
  end

  def call
    cancel
    send_email_notification
  end

  private

  def cancel
    order.cancel!
  end

  def send_email_notification
    CancelOrderMailer.deliver(order)
  end

  def order
    OrderRepository.find(@order_id) or
      error! "Order cannot be found (#{ @order_id })"
  end
end
```

The notification logic above could be a candidate for Observer Pattern, but if you define the algorithm in terms of steps, instead of events, it's simpler and if something goes wrong, you have a better debugging experience.

> Similar to the way Erlang "applications" send messages to each other in a fire and forget fashion.

Ruby VM is not even comparable with Erlang VM (sigh). If you need to achieve this, I suggest to use a persisted queue. For instance, in a real world application, I'd use the following implementation:

```ruby
def send_email_notification
  CancelOrderWorker.perform_async @order_id
end
```

Where `CancelOrderWorker` is a Sidekiq worker. Because sending the email is bound to the network state, it's slow and prone to failures, we want to use "fire and forget" here. The main difference is the fact that Sidekiq is persisted, transparent and has retry policies.

My vote is :-1: for observers, does it make sense for you?
