### ISSUE TITLE
Secure by default?

### ISSUE THREAD

**Issue by thegcat** [lotus/lotus#64]
What is the policy for Lotus regarding security? Should Lotus be (reasonably) secure by default or should this be a responsibility of the developer? (I'm thinking about `rack-protection` for example, I' not so sure about a mechanism similar to `SafeBuffer`)

**Comment by jodosha** [comment]
@thegcat @rkh @lasseebert @activestylus @emptyflask @PragTob @janko-m Folks, I've carefully listened and considered your advices: Lotus [will adopt](http://lucaguidi.com/2015/01/01/a-new-roadmap-for-lotus.html) a **secure by default** policy.

Security is an important aspect of web apps, but it's often underestimated. In my career I've seen companies only allocate budget for features, without a serious investment in security.

Having a framework that educates and protects against the top vulnerabilities would limit the attack surface for those companies.

For instance CSRF is still in the top 10 of OWASP, and that is a low hanging fruit to fix for frameworks.

However, I'm not sure if we'll use `rack-protection`. The first reason is that, security is a complex topic and we can't claim that Lotus is serious about it, by only blindly using it. We want to evaluate case by case, and where a single component from it is useful we'll eventually use it.

My second concern about `rack-protection` is still about perf. Because it's a generic tool, each middleware is designed to run in isolation. For instance, in different middleware, it instantiate several times `Rack::Request` to check params. Because Lotus::Controller, already has a in instantiated set of params, we can directly check them.

I'm closing this as it was a question and not a specific technical issue. I hope my explanation addressed to all your concerns. As usual, I'm open to any further discussion.

**Comment by rkh** [comment]
+1 I'm totally fine with people not using rack-protection as long as there
is some means of protection. I'm also open to refactoring rack-protection
(which I have on my Sinatra 2 roadmap, anyway) to address your issues. I do
believe that there is value in sharing such critical code between projects.

**Comment by jodosha** [comment]
Here are the **security** mechanisms that we want to ship with Lotus v0.3.0: Automatic markup escape, Content-Security-Policy and X-Frame-Options headers, HttpOnly cookies https://discuss.lotusrb.org/t/security-features-for-v0-3-0/34
